export const CREATE_FLEET = "CREATE_FLEET";
export const ACTIVE_STAGE_DETAIL_MODAL = "ACTIVE_STAGE_DETAIL_MODAL";

export const CREATE_WORKFLOW_MODAL = "CREATE_WORKFLOW_MODAL";
export const EDIT_WORKFLOW_MODAL = "EDIT_WORKFLOW_MODAL";

export const CREATE_REASON_MODAL = "CREATE_REASON_MODAL";
export const EDIT_REASON_MODAL = "EDIT_REASON_MODAL";

export const CREATE_ROLE_MODAL = "CREATE_ROLE_MODAL";
export const EDIT_ROLE_MODAL = "EDIT_ROLE_MODAL";

export const CREATE_USER_MODAL = "CREATE_USER_MODAL";
export const EDIT_USER_MODAL = "EDIT_USER_MODAL";

export const CREATE_MATERIAL_MODAL = "CREATE_MATERIAL_MODAL";
export const EDIT_MATERIAL_MODAL = "EDIT_MATERIAL_MODAL";

export const CREATE_STAGE_MODAL = "CREATE_STAGE_MODAL";
export const EDIT_STAGE_MODAL = "EDIT_STAGE_MODAL";

export const CREATE_SUB_STAGE_MODAL = "CREATE_SUB_STAGE_MODAL";
export const EDIT_SUB_STAGE_MODAL = "EDIT_SUB_STAGE_MODAL";

export const CREATE_PROJECT_MODAL = "CREATE_PROJECT_MODAL";
export const EDIT_PROJECT_MODAL = "EDIT_PROJECT_MODAL";

export const CREATE_TRAIN_MODAL = "CREATE_TRAIN_MODAL";
export const EDIT_TRAIN_MODAL = "EDIT_TRAIN_MODAL";

export const CREATE_WAGON_MODAL = "CREATE_WAGON_MODAL";
export const EDIT_WAGON_MODAL = "EDIT_WAGON_MODAL";