import "@fortawesome/fontawesome-svg-core/styles.css";
import "react-loading-skeleton/dist/skeleton.css";
import "../globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import type { Metadata } from "next";

import { AppShell } from "@/components/layout/AppShell";
import styles from "@/styles/Layout.module.scss";

import { Providers } from "./providers";

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Afyon İş Akış Yönetim Sistemi",
  description: "Generated by TMS Arge",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           rel="stylesheet"
//           href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
//         />
//       </head>
//       <body className={styles["layout"]}>
//         <Providers>
//           <AppShell>{children}</AppShell>
//         </Providers>
//       </body>
//     </html>
//   );
// }

import { GoogleAnalytics } from "@next/third-parties/google";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";

// import { CookieContainer } from "@/components/CookieContainer";
// import { Footer } from "@/components/layout/footer/Footer";
// import { Navbar } from "@/components/layout/navbar/Navbar";
import { routing } from "@/i18n/routing";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  const cookieStore = await cookies();
  // const consent = cookieStore.get("cookie-consent");

  if (!routing.locales.includes(locale as "tr" | "en")) {
    notFound();
  }

  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <Providers>
        <AppShell>{children}</AppShell>
      </Providers>
    </NextIntlClientProvider>
  );
}
