import type { Metadata } from "next";

import { config } from "@fortawesome/fontawesome-svg-core";

import { AppShell } from "@/components/layout/AppShell";

import { Providers } from "./providers";

import "@fortawesome/fontawesome-svg-core/styles.css";
import "react-loading-skeleton/dist/skeleton.css";
import "../globals.css";

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Afyon İş Akış Yönetim Sistemi",
  description: "Generated by TMS Arge",
};

import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";

import { routing } from "@/i18n/routing";

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as  "tr" | "en" | "de" | "ru")) {
    notFound();
  }

  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <Providers>
        <AppShell>{children}</AppShell>
      </Providers>
    </NextIntlClientProvider>
  );
}
